import type { Database } from '../database.types';
import type { Job } from '../types';
export declare function getJobs(filters?: {
    status?: 'published';
    keyword?: string;
    location?: string;
    specialty?: string;
    employmentType?: string;
    experienceLevel?: string;
}): Promise<Job[]>;
export declare function getJobById(id: string): Promise<Job | null>;
export declare function createJob(jobData: {
    org_id: string;
    title: string;
    role_type: Database['public']['Enums']['role_type'];
    employment_type: Database['public']['Enums']['employment_type'];
    experience_level: Database['public']['Enums']['experience_level'];
    description: string;
    specialty_tags?: string[];
    requirements?: string;
    responsibilities?: string;
    salary_min?: number;
    salary_max?: number;
    currency?: string;
    city?: string;
    country?: string;
    shift_type?: string;
    benefits?: any;
    new_grad_welcome?: boolean;
    training_provided?: boolean;
    internship_available?: boolean;
    status?: Database['public']['Enums']['job_status'];
}): Promise<Job>;
export declare function updateJobStatus(id: string, status: Database['public']['Enums']['job_status']): Promise<void>;
export declare function saveJob(userId: string, jobId: string): Promise<void>;
export declare function unsaveJob(userId: string, jobId: string): Promise<void>;
export declare function getSavedJobs(userId: string): Promise<Job[]>;
